### PR TITLE
upgraded Shakespeare to TP8

### PR DESCRIPTION
**Pull request by windauer**
upgraded shakespeare to upcoming tei-publisher-app v8 and tei-publisher-lib v3

### CODE REVIEW

**Comment by duncdrum** [comment]
when I open the app from dashboard I keep getting:
```xml
<exception>

<path>/db/apps/shakespeare-pm/modules/lib/api.xql</path>

<message>
err:XQST0059 error found while loading module capi: Error while loading module api/collection.xql: error found while loading module custom: Error while loading module ../../custom-api.xql: error found while loading module app: Error while loading module app.xql: error found while loading module templates: failed to load module: 'http://exist-db.org/xquery/templates' from: 'http://exist-db.org/xquery/templates', location: 'http://exist-db.org/xquery/templates'. Source not found.
</message>
</exception>
```

 The other apps (TP, Van Gogh) are working fine

**Comment by windauer** [comment]
@duncdrum thanks! Its fixed now with commit [b7c0142](https://github.com/eeditiones/shakespeare/pull/8/commits/b7c014278bdfe3f5be19de8d0cb535fd1e335be7)

**Review by duncdrum — APPROVED** [review]
I ll confirm that the templating fix solved the problem later tonight, but from a codereview it should. Once this PR is merged, we need to adjust the URL in https://github.com/eeditiones/tei-publisher-app/pull/149

**Review by duncdrum — COMMENTED** [review]
Ok the page now loads properly. … but:
- I see no documents
- I can't login with not as user `tei`, `guest` or `admin` (I can log into exile or monex or dashboard just fine)
- using the navbar search opens tei-publisher
- there is still a gitlab link in the navbar that goes into http somewhere

**Comment by windauer** [comment]
> Ok the page now loads properly. … but:
> 
> * I see no documents
> * I can't login with not as user `tei`, `guest` or `admin` (I can log into exile or monex or dashboard just fine)
> * using the navbar search opens tei-publisher
> * there is still a gitlab link in the navbar that goes into http somewhere

I was not able to reproduce the behaviour, here it works perfectly fine when building and running the docker image like this (thanks for the help with docker!) 

* `docker build https://github.com/eeditiones/tei-publisher-app.git\#tp8-docker-maintenance -t publisher8`
* `docker run -p 8080:8080 publisher8:latest`

**Comment by duncdrum** [comment]
hmm i checked this again just now on TP main app, van-gogh and Shakespeare I see no documents. 
The browser console 
```
[Error] Unhandled Promise Rejection: TypeError: Illegal constructor
	(anonymous function) (pb-components-bundle.js:716:53751)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```
and 

```
[Error] Failed to load resource: the server responded with a status of 405 (Method Not Allowed) (people, line 0)
```

on the demo apps. 

`exist.log` has multiple instances of 

```
2023-03-13 11:59:23 13 Mar 2023 10:59:23,371 [qtp1761495255-25] ERROR (LogFunction.java [writeLog]:199) - (Line: 521 /exist/etc/../data/expathrepo/roaster-1.8.0/content/router.xql) [d509dbc9-b298-4650-89db-c9b29886503b] post /index.html: 405
2023-03-13 11:59:23             {"code":"errors:METHOD_NOT_ALLOWED_405","description":"The method post is not supported for /index.html","value":null,"line":207,"column":9,"module":"/exist/etc/../data/expathrepo/roaster-1.8.0/content/router.xql"}
```

login does not work for me

tested with macOS12 and macOS13 latest Safari.

the documents are all present in their respective apps `data` collections according to exide

**Pull request merged**
